name: anuga_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - future   
  - gitpython
  - matplotlib
  - dill
  - netcdf4
  - numpy
  - pytest
  - pytz
  - scipy
  - setuptools
  - wheel
  - GDAL
  - wget
  - poppler
  - cython
  - pyproj
  - mpi4py
  - openmpi
  - pip
  - pip:
    - pmw
    - affine 
    - pmw 
    - utm
    - nvtx
    - meshpy
    - pymetrics
    - pytriangle
    - tzdata
    - affine
    - pymetis
    - pandas
    - openpyxl
    - cupy-cuda114